name: Dhall Secret
description: Step up Dhall Secret on Buildkite
author: https://github.com/jcouyang
requirements: [ curl, sha256sum ]
configuration:
  properties:
    os:
      type: string
  additionalProperties: false
